name: Main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  web-deploy:
    name: Wdrazanie
    runs-on: ubuntu-latest
    steps:
    - name: Akcja Github
      uses: action/checkout@v4

    - name: Wdrożenie do FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 172.172.224.46
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_passwords}}
        server-dir: www/
